// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test/proto/test.proto

/*
	Package http is a generated protocol buffer package.

	It is generated from these files:
		test/proto/test.proto

	It has these top-level messages:
		ReqPing
		RespPing
*/
package http

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	zen "github.com/philchia/zen"
	http "net/http"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type ReqPing struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *ReqPing) Reset()                    { *m = ReqPing{} }
func (m *ReqPing) String() string            { return proto1.CompactTextString(m) }
func (*ReqPing) ProtoMessage()               {}
func (*ReqPing) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ReqPing) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type RespPing struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *RespPing) Reset()                    { *m = RespPing{} }
func (m *RespPing) String() string            { return proto1.CompactTextString(m) }
func (*RespPing) ProtoMessage()               {}
func (*RespPing) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RespPing) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto1.RegisterType((*ReqPing)(nil), "proto.ReqPing")
	proto1.RegisterType((*RespPing)(nil), "proto.RespPing")
}

type TestService interface {
	Ping(zen.Context, *ReqPing) (*RespPing, error)
}

func RegisterTestServer(router zen.Router, server TestService) {
	router.Post("test.ping", func(ctx zen.Context) {
		var req = new(ReqPing)
		if err := ctx.BindJSON(req); err != nil {
			ctx.WriteStatus(http.StatusBadRequest)
			return
		}
		resp, err := server.Ping(ctx, req)
		if err != nil {
			ctx.WriteStatus(http.StatusBadRequest)
			return
		}
		ctx.JSON(resp)
	})

}

func init() { proto1.RegisterFile("test/proto/test.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 113 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x49, 0x2d, 0x2e,
	0xd1, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x07, 0x31, 0xf5, 0xc0, 0x4c, 0x21, 0x56, 0x30, 0xa5,
	0x24, 0xcd, 0xc5, 0x1e, 0x94, 0x5a, 0x18, 0x90, 0x99, 0x97, 0x2e, 0x24, 0xc0, 0xc5, 0x9c, 0x5b,
	0x9c, 0x2e, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0x62, 0x2a, 0xc9, 0x70, 0x71, 0x04, 0xa5,
	0x16, 0x17, 0x60, 0x97, 0x35, 0xd2, 0xe7, 0x62, 0x09, 0x49, 0x2d, 0x2e, 0x11, 0x52, 0xe7, 0x62,
	0x01, 0xab, 0xe0, 0x83, 0x98, 0xac, 0x07, 0x35, 0x4f, 0x8a, 0x1f, 0xce, 0x87, 0x18, 0x91, 0xc4,
	0x06, 0xe6, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe1, 0xb6, 0x76, 0xa0, 0x92, 0x00, 0x00,
	0x00,
}
